parameters:
  - name: forceRelease
    type: boolean
    default: false

trigger:
  - main

pr:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: build
    jobs:
      - job:
        steps:
          - checkout: self
            fetchDepth: 0
            fetchTags: true
          - pwsh: |
              Install-Module AzPipelineVariable
          - script: curl https://raw.githubusercontent.com/gembaadvantage/uplift/main/scripts/install | bash
            displayName: install uplift
          - pwsh: |
              $nextVersion = uplift tag --next --silent --no-prefix

              $nextVersion | Set-AzPipelineVariable version
              $null -ne $nextVersion | Set-AzPipelineVariable trigger
            name: release
          - pwsh: .\Build.ps1 -Version $(release.version)
            displayName: build module
          - publish: ./output
            artifact: module
            displayName: publish module artifact
  - stage:
    displayName: publish
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq('${{ parameters.forceRelease }}', 'true')))
    jobs:
      - job:
        steps:
          - checkout: self
            fetchDepth: 0
            fetchTags: true
            persistCredentials: true
          - script: git checkout $(Build.SourceBranchName)
            displayName: checkout triggering branch to get out of detached head state
          - download: current
            artifact: module
            displayName: download module artifact
          - script: curl https://raw.githubusercontent.com/gembaadvantage/uplift/main/scripts/install | bash
            displayName: install uplift
          - script: uplift release
            displayName: uplift